name: Docker Build and Publish

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: docker.io
  # Use GitHub.repository_owner as namespace
  NAMESPACE: ${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-management
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # API Gateway
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-api-gateway:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-api-gateway:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Menu Service
      - name: Build and push Menu Service
        uses: docker/build-push-action@v4
        with:
          context: ./menu-services
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-menu-service:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-menu-service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Order Service
      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./order-services
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-order-service:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-order-service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Customer Service
      - name: Build and push Customer Service
        uses: docker/build-push-action@v4
        with:
          context: ./customer-services
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-customer-service:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-customer-service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Inventory Service
      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-services
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-inventory-service:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-inventory-service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Payment Service
      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./payment-services
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-payment-service:latest,${{ env.REGISTRY }}/${{ env.NAMESPACE }}/cafe-payment-service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }} 